version: "3"
services:

    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./www:/var/www
        #env_file:
        #- ./.env
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        #env_file:
        #- ./.env
        networks:
            - app-network

    npm:
        image: node:13.7
        #image: node:16.15.0-alpine
        container_name: php-npm
        volumes:
            - ./www:/var/www
        ports:
            - 3000:3000
            - 3001:3001
        working_dir: /var/www/
        entrypoint: ['npm']
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
